<a href="https://colab.research.google.com/github/aawizard/Learning_DataSci/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is NumPy?
NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python

In [0]:
import numpy as np

# Basics

In [0]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [0]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [0]:
#getting dimentions
print(a.ndim)
b.ndim

2


3

In [0]:
#get Shape
b.shape

(2, 3)

In [0]:
# Get Type
b.dtype

dtype('float64')

In [0]:
# Get Size i.e size of data type
b.itemsize

8

In [0]:
# Get total size
a.nbytes

6

In [0]:
# Get number of elements
b.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [0]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [0]:
# Get a specific element [r, c]
a[-1,6]

14

In [0]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [0]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [0]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([[2, 4, 6]])

In [0]:
#changing value
a[1,5] = 20

a[:,2] = [1,1]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  1 11 12 20 14]]


In [0]:
#3D example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [0]:
# Get specific element (work outside in)
b[0,1,1]

4

In [0]:

# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [0]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
# All 1s matrix
np.ones((2,3,5),dtype='int16')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [0]:
# Any other number
np.full((2,2), 78)

array([[78, 78],
       [78, 78]])

In [0]:
# Any other number (full_like)
np.full_like(a, 8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [0]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.72356538, 0.09016277],
       [0.1423896 , 0.99510048],
       [0.74045436, 0.70576118],
       [0.30535395, 0.55282875]])

In [0]:
# Random Integer values (min value,max,size)
np.random.randint(-4,8, size=(3,3))

array([[ 3,  7,  7],
       [-2,  7,  6],
       [ 0, -1,  5]])

In [0]:
# The identity matrix
np.identity(5,dtype='int16')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [0]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [0]:
output = np.ones((5,5),dtype='int16')
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:-1,1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Copy and View
Changes made in original array or copied array do not reflect in each other
While they do in View

In [0]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
c=a.view()
a[1]=4
print(a)
print(b)
print(c)

[1 4 3]
[100   2   3]
[1 4 3]


# Mathmatics

In [0]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [0]:
a+2

array([3, 4, 5, 6])

In [0]:
a-2

array([-1,  0,  1,  2])

In [0]:
a*2

array([2, 4, 6, 8])

In [0]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [0]:
#adding two arrays
b=np.array([6,4,3,2])
a+b

array([7, 6, 6, 6])

In [0]:
#square of each element a array
a**2
c=np.array([[1,2],[3,10]])
c**2

array([[  1,   4],
       [  9, 100]])

Many more on https://numpy.org/doc/stable/reference/routines.math.html

# Linear Algebra

In [0]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
#these gives matrix multiplication of two matrices
print(np.matmul(a,b))
print(np.dot(a, b))
print(a@b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [0]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

All on https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

# Stastics

In [0]:
stats = np.array([[1,2,3],[4,5,0]])
stats

array([[1, 2, 3],
       [4, 5, 0]])

In [0]:
np.min(stats)

0

In [0]:
np.max(stats)

5

In [0]:
np.max(stats,axis=1)

array([3, 5])

In [0]:
np.sum(stats, axis=0)

array([5, 7, 3])

# Reorganizing array

In [0]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [0]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [0]:
#splitting array
arr = np.array([1, 2, 3, 4, 5, 6])
#only for 1d array
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [0]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr)
newarr = np.array_split(arr, 3)
#instead of array_split() hsplit() can also be used
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Search and sort

In [0]:
#finding position of an element
arr = np.array([[1, 2, 3],[ 4, 5, 4, ]])

x = np.where(arr == 4)

print(x)

(array([1, 1]), array([0, 2]))


In [0]:
arr==1

array([[ True, False, False],
       [False, False, False]])

In [0]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7,side='right')

print(x)

2


In [0]:
#sorting array row wise
arr = np.array([[3, 2], [0, 1]])

print(np.sort(arr))

[[2 3]
 [0 1]]


In [0]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']
